"""Сделал категории и товары

Revision ID: 62e474514505
Revises: 
Create Date: 2025-06-18 10:32:22.994965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62e474514505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS goods")
    op.create_table('good_category',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=254), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    schema='goods'
                    )
    op.create_table('goods',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('category_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('photo_url', sa.String(), nullable=True),
                    sa.Column('price', postgresql.MONEY(), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['category_id'], ['goods.good_category.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('photo_url'),
                    schema='goods'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods', schema='goods')
    op.drop_table('good_category', schema='goods')
    # ### end Alembic commands ###
