"""create table

Revision ID: e027a3cb2bf4
Revises: 
Create Date: 2025-06-26 14:35:07.903785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e027a3cb2bf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('goods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['public.good_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('goods_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('good_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['public.goods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_url'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_photos', schema='public')
    op.drop_table('goods', schema='public')
    op.drop_table('good_category', schema='public')
    # ### end Alembic commands ###
