"""добавил ограничения

Revision ID: 157af00e2d76
Revises: 968510031db7
Create Date: 2025-07-03 18:45:31.770431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157af00e2d76'
down_revision: Union[str, Sequence[str], None] = '968510031db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_service.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    schema='auth_service'
    )
    op.create_index('idx_tokens_user_id', 'tokens', ['user_id'], unique=False, schema='auth_service')
    op.create_index(op.f('ix_auth_service_tokens_user_id'), 'tokens', ['user_id'], unique=False, schema='auth_service')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='auth_service', type_='unique')
    op.create_index('idx_user_email', 'users', ['email'], unique=False, schema='auth_service')
    op.create_index(op.f('ix_auth_service_users_email'), 'users', ['email'], unique=True, schema='auth_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_service_users_email'), table_name='users', schema='auth_service')
    op.drop_index('idx_user_email', table_name='users', schema='auth_service')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='auth_service', postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_auth_service_tokens_user_id'), table_name='tokens', schema='auth_service')
    op.drop_index('idx_tokens_user_id', table_name='tokens', schema='auth_service')
    op.drop_table('tokens', schema='auth_service')
    # ### end Alembic commands ###
