"""добавил unique на на пользователя

Revision ID: d874d813b3d3
Revises: 157af00e2d76
Create Date: 2025-07-03 18:54:47.024823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd874d813b3d3'
down_revision: Union[str, Sequence[str], None] = '157af00e2d76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_service_tokens_user_id'), table_name='tokens', schema='auth_service')
    op.create_index(op.f('ix_auth_service_tokens_user_id'), 'tokens', ['user_id'], unique=True, schema='auth_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_service_tokens_user_id'), table_name='tokens', schema='auth_service')
    # ### end Alembic commands ###
